### ISSUE TITLE
Controller class could not the found

### ISSUE THREAD

**Issue by arkayz** [cakephp/upgrade#101]
Having an issue after using the upgrade tool where the controllers can't be found, even though they exist and are being referenced properly in the routes.

The error is as follows:
Error: [Cake\Routing\Exception\MissingControllerException] Controller class Home could not be found.
Exception Attributes: array (
  'class' => 'Home',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /
Client IP: xxx.xxx.xxx.xxx
Stack Trace:
#0 /var/www/project/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}

Any idea what the problem might be?

Thanks!

**Comment by markstory** [comment]
Make sure your routes are setup correctly, and that your routes use `PascalCase` names for the controller names. Closing as this isn't a specific issue with the upgrade tool.
