### ISSUE TITLE
version upgrading from 2.3.5 to 2.8.4

### ISSUE THREAD

**Issue by purnarao** [cakephp/upgrade#102]
I tried to update my Cakephp version from 2.3.5 to 2.8.4. I got a solution that we can simply replace the lib folder to upgrade any versions between 2.X. So, I replaced my 2.3.5 version lib folder with the new one . My application is working fine with a warning message that "**Warning: set_error_handler() expects the argument (AppError::handleError) to be a valid callback in \lib\Cake\Core\Configure.php on line 473**". I tried by comparing my new files with old files. But, couldn't relocate this issue. Does any one can help me out from this.

**Comment by dereuromark** [comment]
This is for 3.x migration, for 2.x see https://github.com/dereuromark/cakephp-upgrade etc
