### ISSUE TITLE
blank page after upgrade to 3.0 from 2.5.5

### ISSUE THREAD

**Issue by nbouida** [cakephp/upgrade#106]
Hi,

I am getting a blank page in localhost after upgrading cakephp from 2.5.5 to 3.0 by using the upgrade tool.

I have checked all prerequisites (PHP 7.0 + mbstring and intl extension are present).

Thanks for your help.

**Comment by markstory** [comment]
There isn't much we can do from here. Turn on error reporting and display errors and work your way through the various errors that come up. While the upgrade tool takes care of some mechanical changes that can be done, there is often a sizable bit of manual work that is required to complete an upgrade from 2.x to 3.x.
