### ISSUE TITLE
Valet-linux installation PHP fatal error

### ISSUE THREAD

**Issue by MohammadShawon** [cakephp/upgrade#107]
PHP Fatal error:  Cannot declare class Nginx, because the name is already in use in /home/codemagic/.composer/vendor/cpriego/valet-linux/cli/includes/facades.php on line 32

**Comment by markstory** [comment]
There is no [class named Nginx](https://github.com/cakephp/upgrade/search?utf8=%E2%9C%93&q=Nginx) in this repository.
