### ISSUE TITLE
Site does not working after upgrade .

### ISSUE THREAD

**Issue by deveshpandyadc** [cakephp/upgrade#108]
I have used all commands but after successfully run commands not working.
XXXX.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by josegonzalez** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by deveshpandyadc** [comment]
Thanks

**Comment by deveshpandyadc** [comment]
So I have to upgrade to 2.3 then 2.4 then so on .After 2.9 I have to upgrade into 3.0 .Am I right ?
