### ISSUE TITLE
The "use" keyword is detected in strings

### ISSUE THREAD

**Issue by rhaist** [cakephp/upgrade#110]
The "use" keyword is detected in some php strings and leads to deletion of such sections and faulty code.
Example:

https://github.com/MISP/MISP/issues/2350#issuecomment-317251295

**Comment by burzum** [comment]
This regex should match all the App::uses() calls `App::uses\('(.*)',( *)'(.*)'\);` and put both args in two matching groups. It's a start, we just need to match and add them on top :)

**Comment by othercorey** [comment]
Closing 2.x => 3.x issues.
