### ISSUE TITLE
The "locations" command generates weird paths

### ISSUE THREAD

**Issue by rhaist** [cakephp/upgrade#111]
Running the locations command on the @MISP codebase generated some weird paths:

```
        renamed:    app/View/Layouts/Emails/html/default.ctp -> app/src/src/src/Template/Layout/Email/html/default.ctp
        renamed:    app/View/Layouts/Emails/text/default.ctp -> app/src/src/src/Template/Layout/Email/text/default.ctp
```

**Comment by markstory** [comment]
Did other view templates get moved in a similarly strange way?

**Comment by SleuthKid** [comment]
Yes. The shown lines where only meant as an example. I can attach more if necessary.

You can also test it yourself if you want by running the latest version against the @MISP app folder.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SleuthKid** [comment]
Yes. The shown lines where only meant as an example. I can attach more if necessary.

You can also test it yourself if you want by running the latest version against the @MISP app folder.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wsergent** [comment]
Same issue just now attempting to upgrade from 2.1.5 to latest 3.7 build
A quick example of the folder structure post `bin/cake upgrade all /c/wamp/www/project-folder`

![image](https://user-images.githubusercontent.com/7488024/54101587-90c14580-4418-11e9-9efe-daeab4274863.png)

That looks nothing like a standard CakePHP 3 folder structure, and I have multiple nested `src` folders containing a random mix of files.

Looks as though the Upgrade Tool is completely unusable for this project. Was hoping this would save a lot of time, but no luck. Am going to step through a couple of version migrations and try again after each to see what the result is - it may be that the tool works better after a certain version, and 2.1.5 is simply too old.

**Comment by othercorey** [comment]
> Same issue just now attempting to upgrade from 2.1.5 to latest 3.7 build

Why upgrade from such an early version of 2.x?  Shouldn't you be upgrading to latest 2.x before upgrading to 3.x?

**Comment by wsergent** [comment]
> Why upgrade from such an early version of 2.x? Shouldn't you be upgrading to latest 2.x before upgrading to 3.x?

Because the tool explicitly says that it could handle such an upgrade?
If you'd read further than my opening line,  you'd see that that was pretty much the outcome I came to 10 months ago.

**Comment by othercorey** [comment]
Closing 2.x => 3.x issues.
