### ISSUE TITLE
Error running project after upgrade

### ISSUE THREAD

**Issue by GustavoGiraldo** [cakephp/upgrade#117]
Hi
After the update, I open the project and get the following error:

Parse error: syntax error, unexpected 'use' (T_USE) in C:\wamp64\www\rootcake3\lib\Cake\basics.php on line 85

What can I do?
Thanks

**Comment by markstory** [comment]
You need at least php 5.3 or there is a missing semicolon/ other syntax error in the named file.

**Comment by GustavoGiraldo** [comment]
The code that has error is:

if (!function_exists('debug')) {
    /**
     * Prints out debug information about given variable.
     *
     * Only runs if debug level is greater than zero.
     *
     * @param boolean $var Variable to show debug information for.
     * @param boolean $showHtml If set to true, the method prints the debug data in a browser-friendly way.
     * @param boolean $showFrom If set to true, the method prints from where the function was called.
     * @return void
     * @link http://book.cakephp.org/2.0/en/development/debugging.html#basic-debugging
     * @link http://book.cakephp.org/2.0/en/core-libraries/global-constants-and-functions.html#debug
     */
    function debug($var, $showHtml = null, $showFrom = true)
    {
        if (Configure::read('debug') > 0) {
            use App\Utility\Debugger;
            $file = '';
            $line = '';
            $lineInfo = '';
            if ($showFrom) {
                $trace = Debugger::trace(array('start' => 1, 'depth' => 2, 'format' => 'array'));
                $file = str_replace(array(CAKE_CORE_INCLUDE_PATH, ROOT), '', $trace[0]['file']);
                $line = $trace[0]['line'];
            }
            $html = <<<HTML
<div class="cake-debug-output">
%s
<pre class="cake-debug">
%s
</pre>
</div>
HTML;
            $text = <<<TEXT
%s
########## DEBUG ##########
%s
###########################
TEXT;
            $template = $html;
            if (PHP_SAPI === 'cli' || $showHtml === false) {
                $template = $text;
                if ($showFrom) {
                    $lineInfo = sprintf('%s (line %s)', $file, $line);
                }
            }
            if ($showHtml === null && $template !== $text) {
                $showHtml = true;
            }
            $var = Debugger::exportVar($var, 25);
            if ($showHtml) {
                $template = $html;
                $var = h($var);
                if ($showFrom) {
                    $lineInfo = sprintf('<span><strong>%s</strong> (line <strong>%s</strong>)</span>', $file, $line);
                }
            }
            printf($template, $lineInfo, $var);
        }
    }
}

I do not see a semicolon problem

**Comment by GustavoGiraldo** [comment]
![captura](https://user-images.githubusercontent.com/12173557/38700817-e35077ca-3e61-11e8-8263-a0cd020f7ea4.PNG)

**Comment by markstory** [comment]
That looks like the CakePHP code, which you shouldn't run the upgrade tools on as they are installed via composer in a 3.x application.

**Comment by GustavoGiraldo** [comment]
what I did was download the update tool and execute the upgrade commands in the proper order
Then I opened the updated project and the error came out:
syntax error, unexpected 'use' (T_USE) in

**Comment by markstory** [comment]
Ok. But the upgrade tool is only supposed to be run on the app and plugins. The documentation assumes that you're using composer for installing cakephp.

**Comment by GustavoGiraldo** [comment]
I have a question.
the command would be:
bin/cake upgrade locations /path/to/appcakephp2x ??????

**Comment by markstory** [comment]
I think so? It has been years since I have used this code to be honest.

**Comment by rajdipchauhan** [comment]
@GustavoGiraldo Have you got the solution for this error? or is there any other way to upgrade the CakePHP version?
