### ISSUE TITLE
Fatal error while following 4.x upgrade instructions.

### ISSUE THREAD

**Issue by niel** [cakephp/upgrade#128]
Running:
`bin/cake upgrade rector --rules phpunit80 <path/to/app/tests>`
produces a fatal error 9% (12/123) in.

Fatal error: Declaration of Cake\TestSuite\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/niel/dev/www/cake-test/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 35

**Comment by niel** [comment]
Once the `: void` is added to the setUp and tearDown methods for this file, the same has to be down for any tests in the app itself.

**Comment by markstory** [comment]
@niel How did you install the upgrade tool? I've seen that error come up when it is installed with dev dependencies (which include phpunit, or if your application's dependencies are updated before running the rector tasks.

**Comment by niel** [comment]
The upgrade tool was installed folling the instructions at https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html
My application was uodated to latest CakePHP and dependencies before trying to run the upgrade tool.
NOTE that the files that needed to be "fixed" with return types were in my application's vendor's directory - i.e. its dependencies.

**Comment by markstory** [comment]
Thanks, how did you run the rector tasks? The current docs recommend that you run phpunit8 changes only against your test directory and not the vendor directory.

**Comment by niel** [comment]
I ran the tests as per the instructions on the page linked above:

`bin/cake upgrade rector --rules phpunit80 <path/to/app/tests>`

**Comment by markstory** [comment]
Interesting, I wonder how it got into your vendor directories then. Are you confident that rector task was modifying the vendor files or were they just autoloaded?

**Comment by niel** [comment]
I'm pretty sure they were just being autoloaded because they're dependencies for the app being tested.

**Comment by fr3nch13** [comment]
I'm getting this error before upgrading to CakePHP 4.x from 3.8.x

It seems to be loading cakephp from the project's vendor files, and not cakephp/upgrade's vendor files.
This is causing the error:
```bash
PHP Fatal error:  Declaration of Cake\TestSuite\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /mnt/c/Users/frenchbm/Projects/fr3nch13/cakephp-jira/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 35
Fatal error: Declaration of Cake\TestSuite\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /mnt/c/Users/frenchbm/Projects/fr3nch13/cakephp-jira/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 35
```

Which would technically be true since CakePHP in the projects vendor folder is still 3.8.x
In my case 3.8.7 at /mnt/c/Users/frenchbm/Projects/fr3nch13/**cakephp-jira/vendor/cakephp/cakephp/src/TestSuite/TestCase.php**

**Comment by markstory** [comment]
@fr3nch13 ok, but that cakephp install would have a compatible phpunit version installed which is why I think it might be a dev dependency issue.

**Comment by fr3nch13** [comment]
Can this one be closed?
