### ISSUE TITLE
Upgrading 3.8 to 4: Fatal Error on Cake\I18n\Time::isThisWeek()

### ISSUE THREAD

**Issue by hagen00** [cakephp/upgrade#136]
When trying to update from the latest Cake3.8 to 4. 
`bin/cake upgrade rector --rules cakephp40 /var/www/code/src` 
results in
```
PHP Fatal error:  Declaration of Cake\I18n\Time::isThisWeek() must be compatible with Cake\Chronos\MutableDateTime::isThisWeek(): bool in /var/www/code/vendor/cakephp/cakephp/src/I18n/Time.php on line 27
```

**Comment by victoreassis** [comment]
This can be solved by using ```composer install --no-dev``` on the upgrade tool as per the documentation: https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html

I think they could be more explicit on the docs as this seems to be required to avoid this conflict.

**Comment by markstory** [comment]
I thought I had removed the `requireDev` section but it has found its way back in. I'll remove it once again.
