### ISSUE TITLE
Fatal error while running rector command on my project

### ISSUE THREAD

**Issue by frankvanhest** [cakephp/upgrade#139]
Today I was trying out the upgrade tool to upgrade 3.8 to 4.0, but I ran into some trouble concerning abstract methods inside one of my classes. The error I got was:
```
PHP Fatal error:  Class AnonymousClassa7eb19d061f5a2423b918ce16819fb6a contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (App\Lib\RootNet\Mpu\AbstractMpuHelper::retrieveLogScope, App\Lib\RootNet\Mpu\AbstractMpuHelper::retrieveRequestDataNamespace, App\Lib\RootNet\Mpu\AbstractMpuHelper::retrieveResponseDataNamespace) in phar:///home/vagrant/code/cakephp-upgrade/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvi
der.php(134) : eval()'d code on line 7
```
The command I run was `bin/cake upgrade rector --rules cakephp40 ../backend/src/`.

Is this normal behaviour or am I doing something wrong here?

**Comment by garas** [comment]
It looks that your app has some _non-abstract_ class which extends _abstract_ class `App\Lib\RootNet\Mpu\AbstractMpuHelper`, but has no `retrieveLogScope`, `retrieveRequestDataNamespace`, `retrieveResponseDataNamespace` methods implemented.

It would fail too in normal process if app would try to use that class. Either implement those methods, remove class or mark class as abstract.

**Comment by frankvanhest** [comment]
My first thought was that maybe phpstan created some anonymous class, but it turns out that in some old code in the project, an anonymous class was created which extended the `AbstractMpuHelper` and didn't implement all the abstract methods. Thanks for your help @garas!
