### ISSUE TITLE
Upgrade from 3.9.x to 4.0: bin/cake upgrade rector --rules phpunit80 Hangs

### ISSUE THREAD

**Issue by dividedbynothing** [cakephp/upgrade#140]
Hi,
I'm upgrading a CakePHP 3.9 app to CakePHP 4, and following the Upgrade Guide.
However, the bin/cake upgrade rector --rules phpunit80 <path/to/app/tests> tools hang.

Environment:
Running XAMPP 7.4.1 on Windows 10 
PHP Version 7.4.1
Current CakePHP version of my app: 3.9 (upgraded successfully from 3.6->3.7->3.8->3.9 with deprecations cleaned up along the way)

I'm following the [CakePHP 4.0 upgrade guide.](https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html) All steps are successful up to "Applying Rector Refactorings".

When I run this:`PS C:\xampp\htdocs\my_app\upgrade> bin/cake upgrade rector --rules phpunit80 C:\xampp\htdocs\my_app\tests` I get this result:
`Rector v0.7.26`

`0/189 [>---------------------------]   0%`
And then it just hangs there.  The same thing happens with  `bin/cake upgrade rector --rules cakephp40`

My PHP Error logs show:
For `bin/cake upgrade rector --rules phpunit80 C:\xampp\htdocs\my_app\tests` the errors show:

`PHP Notice: Undefined property: PhpParser\Node\Expr\ArrayItem::$unpack in C:\xampp\htdocs\my_app\upgrade\vendor\nikic\php-parser\lib\PhpParser\PrettyPrinter\Standard.php on line 558`

For `bin/cake upgrade rector --rules cakephp40` I get the same error as above, and  an additional one:  

`PHP Notice: Undefined property: PhpParser\Node\Expr\ArrayItem::$unpack in phar://C:/xampp/htdocs/my_app/upgrade/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php on line 846` and then the tool hangs again.

When I run `composer show --installed` in my `C:/xampp/htdocs/my_app/upgrade` folder, I see:
rector/rector v0.7.26
phpstan/phpstan 0.12.25
nikic/php-parser v4.4.0

I tried to get through this [over here](https://stackoverflow.com/questions/62097953/cakephp-upgrade-from-3-9-x-to-4-0-bin-cake-upgrade-rector-rules-phpunit80-ha), but no luck.

Any advice or help you might offer here would would be great.
Thanks!
D.

**Comment by markstory** [comment]
Did you install the upgrade tool as a standalone application or in your application as a plugin? It is hard to tell from the paths you've provided.

**Comment by dividedbynothing** [comment]
I basically followed the upgrade guide.  I'm running Xampp on Windows 10.
My app is located at `C:\xampp\htdocs\my_app\`.

So to install the upgrade tool, I run this command in powershell:
`PS C:\xampp\htdocs\my_app> git clone git://github.com/cakephp/upgrade`

This installs the tool in `C:\xampp\htdocs\my_app\upgrade`.  I then follow the command sequence from the upgrade guide.

Note, I managed to get the refactoring to work (sort of), after downgrading the app to 3.8.12 (was 3.9.0-RC2), and fixing a few other errors.  The rector command now seems to complete updating all the files, but still hangs while outputting results in the shell.

I am going to try to reproduce the error with a simpler, clean app, as I want to make sure that "noise" in my main project isn't causing the issue.   I will report back here the results.

**Comment by dividedbynothing** [comment]
Hi,
So I decided to setup a clean, new 3.8 app and then test the upgrade.  Here are my results:

`composer create-project --prefer-dist cakephp/app:^3.8 my_app_name`

Everything installs correctly. CAKE version 3.8.12 (running on PHP Vresion 7.4.1).
Baked all models, controllers, etc.  Didn't change anything.  Everything works fine, no deprecation warnings

Now to upgrade to 4.0 (using windows powershell):
Run:
`PS C:\xampp\htdocs\my_app_name> git clone git://github.com/cakephp/upgrade`
This created directory C:\xampp\htdocs\my_app_name\upgrade

Run:
`PS C:\xampp\htdocs\my_app_name> cd upgrade`
`PS C:\xampp\htdocs\my_app_name\upgrade> git checkout master`
Result:
```
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```
Run:
`PS C:\xampp\htdocs\my_app_name\upgrade> composer install --no-dev`
Everything installs, with the final output message: `Class Cake\Composer\Installer\PluginInstaller is not autoloadable, can not call post-autoload-dump script`

Run:
`PS C:\xampp\htdocs\my_app_name\upgrade> bin/cake upgrade file_rename locales C:\xampp\htdocs\my_app_name`
Done, no locales setup, so no output.

Run:
`PS C:\xampp\htdocs\my_app_name\upgrade> bin/cake upgrade file_rename templates C:\xampp\htdocs\my_app_name`
Result:
```
Moving sub directories of C:\xampp\htdocs\my_app_name\templates
Recursively changing extensions in C:\xampp\htdocs\my_app_name\templates
```
Now, I updated my Changed my app.php to be:
```
        'paths' => [
            'plugins' => [ROOT . DS . 'plugins' . DS],
            'templates' => [ROOT . DS . 'Template' . DS],
            'locales' => [ROOT . DS . 'Locale' . DS],
```

Run:
`PS C:\xampp\htdocs\my_app_name\upgrade>bin/cake upgrade rector --rules phpunit80 C:\xampp\htdocs\my_app_name\tests`
Result:
Lots of output showing changes, with the final message:
```
 [OK] Rector is done! 3 files have been changed.
Rector applied successfully
```
Run:
`PS C:\xampp\htdocs\my_app_name\upgrade> bin/cake upgrade rector --rules cakephp40 C:\xampp\htdocs\my_app_name\src`
Result:
Lots of output, finally outputting:
```
 [OK] Rector is done! 6 files have been changed.
Rector applied successfully
```
So far so good.  Made a backup here.
Now I navigate back to `C:\xampp\htdocs\my_app_name`
Run:
`PS C:\xampp\htdocs\my_app_name> composer require --update-with-dependencies "phpunit/phpunit:^8.0"`
Result:
Looks successful.  Shows `Updates 12 packages, removes 1.` and other details.

Run:
`PS C:\xampp\htdocs\my_app_name> composer require --update-with-dependencies "cakephp/cakephp:4.0.*"`
Result:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/bake 1.12.0 requires cakephp/cakephp ^3.8.0 -> satisfiable by cakephp/cakephp[3.8.0, 3.8.0-RC1, 3.8.0-RC2, 3.8.0-RC3, 3.8.0-beta1, 3.8.1, 3.8.10, 3.8.11, 3.8.12, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.8.7, 3.8.8, 3.8.9, 3.9.0-RC1, 3.9.0-RC2, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - cakephp/bake 1.12.0 requires cakephp/cakephp ^3.8.0 -> satisfiable by cakephp/cakephp[3.8.0, 3.8.0-RC1, 3.8.0-RC2, 3.8.0-RC3, 3.8.0-beta1, 3.8.1, 3.8.10, 3.8.11, 3.8.12, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.8.7, 3.8.8, 3.8.9, 3.9.0-RC1, 3.9.0-RC2, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - cakephp/bake 1.12.0 requires cakephp/cakephp ^3.8.0 -> satisfiable by cakephp/cakephp[3.8.0, 3.8.0-RC1, 3.8.0-RC2, 3.8.0-RC3, 3.8.0-beta1, 3.8.1, 3.8.10, 3.8.11, 3.8.12, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.8.7, 3.8.8, 3.8.9, 3.9.0-RC1, 3.9.0-RC2, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for cakephp/bake (locked at 1.12.0, required as ^1.9.0) -> satisfiable by cakephp/bake[1.12.0].

Installation failed, reverting ./composer.json to its original content.
```
I also tried running the --update-with-dependencies commands inside the upgrades folder, but that phpunit/phpunit:^8.0 upgrade fails, and the cakephp/cakephp:4.0. upgrade finishes but doesn't upgrade the app (it isn't supposed to tun in upgrades, I assume.

Anyway, for now I think my approach will be to use the upgrade tools to do the file names and refactoring, then use those in a clean install of Cake 4.0.

**Comment by othercorey** [comment]
> I also tried running the --update-with-dependencies commands inside the upgrades folder, but that phpunit/phpunit:^8.0 upgrade fails, and the cakephp/cakephp:4.0. upgrade finishes but doesn't upgrade the app (it isn't supposed to run in upgrades, I assume.

Definitely not.

> cakephp/bake 1.12.0 requires cakephp/cakephp ^3.8.0

This isn't an upgrade issue. Composer is telling you what's wrong.

**Comment by dividedbynothing** [comment]
OK. Rector worked anyway.
