### ISSUE TITLE
Call to undefined method PhpParser\Comment\Doc::getStartTokenPos()

### ISSUE THREAD

**Issue by paolini** [cakephp/upgrade#141]
I get the error 

`Call to undefined method PhpParser\Comment\Doc::getStartTokenPos()`

When executing the following command:

`bin/cake upgrade rector --rules phpunit80 <path_to_tests>`

Probably related to: https://github.com/rectorphp/rector/issues/3160

**Comment by dereuromark** [comment]
Is this solved on latest version?

**Comment by LordSimal** [comment]
I'd expect this is solved with all the rector updates which have happened in the past few years.
