### ISSUE TITLE
Custom Database Types are upgraded as TypeFactory

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/upgrade#142]
I tried upgrade a CakePHP 3.9 to 4.x using `bin/cake upgrade rector --rules cakephp40 <src>` and noticed my custom defined types have their base class changed from `Cake\Database\Type` to `Cake\Database\TypeFactory`

I think the rule applied is https://github.com/rectorphp/rector/blob/master/config/set/cakephp/cakephp40.yaml#L6

Should the rule change `Cake\Database\Type` to `Cake\Database\Type\BaseType` instead?

**Comment by markstory** [comment]
This is tricky as `Type` was previously used as both the factory/registry for types *and* the base class. :cry:

**Comment by CauanCabral** [comment]
I see.

Well, are just a couple of Type classes, easy to fix by hand, don't worry.
