### ISSUE TITLE
Upgrade tool rector does not work on Cakephp 3.8.12

### ISSUE THREAD

**Issue by mcube27** [cakephp/upgrade#148]
Hi,

I use CakePhp 3.8.12, php 7.4, win 10 and installed the upgrade tool in another folder than my cakephp folder.

I ran the up `bin\cake upgrade rector --rules cakephp40 ..\relative\path\to\cakephp` with debug mode because it got stuck at 0/412 => 0%

Here is the error I got :
```
Applying cakephp40 Rector rules
File "C:\webserver\www\cakephpUpgradeTool/vendor/autoload.php" is about to be loaded in "AutoloadIncluder::includeCwdVendorAutoloadIfExists()" on line 98"

Fatal error: Uncaught Error: Call to undefined method PhpParser\Comment::getEndLine() in phar://C:/webserver/www/cakephpUpgradeTool/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:700
Stack trace:
#0 phar://C:/webserver/www/cakephpUpgradeTool/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser
/lib/PhpParser/Parser/Php7.php(361): PhpParser\ParserAbstract->createCommentNopAttributes(Array)
#1 phar://C:/webserver/www/cakephpUpgradeTool/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser
/lib/PhpParser/ParserAbstract.php(238): PhpParser\Parser\Php7->PhpParser\Parser\{closure}(17)
#2 phar://C:/webserver/www/cakephpUpgradeTool/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser
/lib/PhpParser/ParserAbstrac
File "C:\webserver\www\cakephpUpgradeTool\vendor\rector\rector/../../autoload.php" is about to be loaded in 
"AutoloadIncluder::autoloadProjectAutoloaderFile()" on line 132"
Rector v0.8.6

[parsing] Application.php

c/php-parser/lib/PhpParser/ParserAbstract.php(142): PhpParser\ParserAbstract->doParse()
#3 phar://C:/webserver/www/cakephpUpgradeTool/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser
/lib/PhpParser/Parser/Multiple.php(48): PhpParser\ParserAbstract->parse('<?php\n/**\n * Ca...', Object(PhpPa in phar://C:
/webserver/www/cakephpUpgradeTool/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser
/ParserAbstract.php on line 700
```
During composer install --no-dev I also has this error :
`Class Cake\Composer\Installer\PluginInstaller is not autoloadable, can not call post-autoload-dump script`

And for windows user, it doesn't work when a folder has a space in its name.

Hope there is something to be done !

Thank you very much

**Comment by markstory** [comment]
Not sure what is going on there. It looks like you've hit an issue with one of rector's dependencies. How did you install the upgrade tool?

**Comment by mcube27** [comment]
As explained in the doc. 

Git clone --no-dev -> composer install

In a seperate directory.

**Comment by mcube27** [comment]
@markstory could look into it or give me some advice on how to solve it ?

Thank you very much

**Comment by markstory** [comment]
You could try running rector directly with `vendor/bin/rector process --autolad-file=path/to/your/autoload.php --set=cakephp40 --working-dir=path/to/your/app/src`

**Comment by netfly** [comment]
I have the same issue here .... when I run rector directly I get a lot of errors but at least it runs.

**Comment by markstory** [comment]
@netfly Not sure about that. You're getting errors from the bowels of the PHP parsers that rector uses.

**Comment by netfly** [comment]
> @netfly Not sure about that. You're getting errors from the bowels of the PHP parsers that rector uses.

Today I just created a ddev (Docker-Container) with PHP 7.3 and everything worked like a charm. It seams to be a Problem of my PHP 7.4.11

**Comment by mcube27** [comment]
@netfly you have tried to call rector directly or the upgrade tool directly with docker and php 7.3 ?

**Comment by netfly** [comment]
> @netfly you have tried to call rector directly or the upgrade tool directly with docker and php 7.3 ?

the update tool (in the docker)

**Comment by mcube27** [comment]
I will try php 7.3 too then, thank you for the update

**Comment by mcube27** [comment]
It does work as rector confirm `[OK] Rector is done!`, however, no single file is modified in my src or in my tests.

Is it normal ?

**Comment by netfly** [comment]
It's definitely php7.4 .... because I switched locally back to php7.3 (not Docker) and it also works.

@markstory You should probably mention this in the docu.
Anyway .... great tool. Thanks a lot

**Comment by mcube27** [comment]
Ok I finally got it working.

This issue was that my autoload also contained a nikic/php-parser due to psy/psysh.

I had to update with dependencies to make rector work.

**Comment by netfly** [comment]
Jep ... this is the "real" solution. I had the same situation. After upgrading nikic/php-parser in my target-project, everything worked great. 
Why I had the issue with the php version, I don't understand.

**Comment by othercorey** [comment]
Did you both have the same version? Might be useful to see if rector can set a valid minimum. You would need to discuss with them though.

**Comment by netfly** [comment]
> Did you both have the same version? Might be useful to see if rector can set a valid minimum. You would need to discuss with them though.

I had 4.8 and upgraded to 4.10

**Comment by mcube27** [comment]
I had nikic/php-parser 4.0.2 and updated to 4.10.2.

I don't know how they can prevent this as using the upgrade tool as a standalone project and the cakephp app as another project, it looks like the rector tool combines the two vendors folders.

I guess, the upgrade tool should check this directly as it's the cakephp app that caused the issue.

I hope it's understandable...

**Comment by othercorey** [comment]
I think the autoloading in rector might be broken.

**Comment by dereuromark** [comment]
It works with .../src subfolders etc as documented.
