### ISSUE TITLE
Rector hangs duting upgrade

### ISSUE THREAD

**Issue by menshutin** [cakephp/upgrade#149]
I did an upgrade from 3.9 to 4.0 following the instruction in manual.
I run the rector with the following command `bin/cake upgrade rector --rules cakephp40 /var/www/test2/src/ -v`
After doing some job it hanged after
`
 504/720 [▓▓▓▓▓▓▓��
 * Rector\Generic\Rector\ClassMethod\AddReturnTypeDeclarationRector
 * Rector\TypeDeclaration\Rector\ClassMethod\AddParamTypeDeclarationRector
`

and running processes are `ps -ax|grep php`:
`php /var/www/upgrade/bin/cake.php upgrade rector --rules cakephp40 /var/www/test2/src/ -v
12853 pts/0    S+     0:38 php /var/www/upgrade/vendor/bin/rector process --autoload-file=/var/www/test2/vendor/autoload.php --set=cakephp40 --working-dir=/var/www/test2/src /var/www/test2/src
`

What should I do to resolve the issue?

**Comment by markstory** [comment]
You could try re-running the command on a subdirectory so it has fewer files to look at. You could be running out of memory.

**Comment by menshutin** [comment]
If I run it again it competes all steps but logs a lot of errors and warnings. 
Some warnings are related to the fixes done by rector at the first pass.
But there are a lot of errors with the following message **Namespace declaration statement has to be the very first statement in the script:7**. The php file with this error looks ok with namescape declaration in right place.
Is it safe to run it multiple times on the same files?

**Comment by markstory** [comment]
>  Is it safe to run it multiple times on the same files?

It should be. Rector generally works toward a consistent state from my experience.
