### ISSUE TITLE
file_rename temlates issue

### ISSUE THREAD

**Issue by ahmedsafroot** [cakephp/upgrade#151]
i runed bin/cake upgrade file_rename templates but in first some files renamed and some no and get error in file name has space i renamed it then try again same command to complete rename file but i get no action as screenshot .
please help @markstory @jippi @jrbasso @renan @AD7six 

![Capture](https://user-images.githubusercontent.com/27191575/97434368-963e0d00-1927-11eb-865d-4efea9f3e1a0.PNG)

**Comment by ahmedsafroot** [comment]
@markstory any advise please

**Comment by markstory** [comment]
@ahmedsafroot I don't know, did the files get renamed? If not try using the `--verbose` flag.

**Comment by williamdes** [comment]
Same for me, no ouput

**Comment by williamdes** [comment]
```
williamdes@williamdes:/mnt/Dev/@phpmyadmin/error-reporting-server$ ../upgrade-cake/bin/cake upgrade file_rename templates $PWD/src/
williamdes@williamdes:/mnt/Dev/@phpmyadmin/error-reporting-server$ ../upgrade-cake/bin/cake upgrade file_rename templates $PWD/
Moving sub directories of /mnt/Dev/@phpmyadmin/error-reporting-server/templates
Recursively changing extensions in /mnt/Dev/@phpmyadmin/error-reporting-server/templates
```

Conclusion: use root folder and read the [readme](https://github.com/cakephp/upgrade#usage)

This is because:

https://github.com/cakephp/upgrade/blob/edacefdf70c81b99aba9e2941452de0df31d5c0d/src/Command/FileRenameCommand.php#L120

**Comment by markstory** [comment]
Would having verbose output that outlined what each step was doing have helped debug this problem?

**Comment by williamdes** [comment]
> Would having verbose output that outlined what each step was doing have helped debug this problem?

A message to warn about no folder found to migrate would have been perfect
