### ISSUE TITLE
upgrade all: Got 1 argument but only 1 arguments are defined

### ISSUE THREAD

**Issue by DJAxel** [cakephp/upgrade#156]
Not sure if this is an issue with the package or with my system, but when running `bin/cake upgrade all /home/mark/Sites/my-app` I get the following error:

```bash
Error: Received too many arguments. Got 1 but only 1 arguments are defined.
```
That's weird, since 1 == 1.

## Reproduction
```bash
git clone https://github.com/cakephp/upgrade.git
cd upgrade/
git checkout -b 3.x
composer install
bin/cake upgrade all /home/mark/Sites/my-app
```

It doesn't matter if I link to Mark's example path, or a path that is actually pointing to a CakePHP 2.10.24 project:
```bash
bin/cake upgrade all /opt/lampp/htdocs/my-app/
```

**Comment by DJAxel** [comment]
It does seem to do something when no argument is provided, but that's not much usefull as I can't specify the project I want to upgrade:

```bash
$ bin/cake upgrade all

Moving templates
Moving locale files
Applying cakephp40 Rector rules
The <info></info> does not exist, skipping.
The <info></info> does not exist, skipping.
The <info></info> does not exist, skipping.
The <info></info> does not exist, skipping.
Applying phpunit80 Rector rules
The provided path `/tests` does not exist.
Next upgrade your composer.json.
```

**Comment by DJAxel** [comment]
Looks like the right command should be without the `all` word:

```bash
bin/cake upgrade /opt/lampp/htdocs/my-app/
```

It's still not doing a lot that way, but at least it recognized the path. Is it possible that the 4.x branch was merged into the 3.x branch by mistake?

**Comment by markstory** [comment]
> It's still not doing a lot that way, but at least it recognized the path. Is it possible that the 4.x branch was merged into the 3.x branch by mistake?

No. The code in the repository is quite different for the 3.x and 4.x versions.

**Comment by DJAxel** [comment]
Well I have searched for the mentioned commands `skeleton`, `locations`, `namespaces`, `app_uses`, etc. but they are nowhere defined in the 3.x branch in any file. It also looks like the Upgrade shell will just run all these commands and not check any of the arguments for this. That's why I thought either the code or the readme.md might have been mixed up.

**Comment by othercorey** [comment]
Why is it applying the 40 rector rules to a 2.x app?

Also, you shouldn't use the -b option to checkout 3.x branch:

> git checkout 3.x

**Comment by garas** [comment]
Reinstall with `git clone https://github.com/cakephp/upgrade.git -b 3.x`. Previous instructions were invalid.

**Comment by garas** [comment]
Previous instructions created local `3.x` branch pointing at remote `master` branch so you used 4.x version instead.
