### ISSUE TITLE
upgrade tool does not work with rule cakephp42

### ISSUE THREAD

**Issue by Tietew** [cakephp/upgrade#159]
I ran the upgrade tool according to 4.2 Migration Guide.
But it died with following message:

```
$ git clone https://github.com/cakephp/upgrade
$ cd upgrade
$ composer install --no-dev
$ bin/cake upgrade rector --rules cakephp42 ~/path/to/myproduct/src/


 [ERROR] File "/path/to/cakephp/upgrade/config/rector/cakephp42.php"
         was not found


Rector applied successfully
```

PHP version:
```
$ php -v
PHP 7.4.15 (cli) (built: Feb 23 2021 15:12:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by othercorey** [comment]
What version of rector was downloaded?

**Comment by Tietew** [comment]
``` sh
$ jq '.packages[]|select(.name=="rector/rector").version' < composer.lock
"0.9.31"
```

**Comment by garas** [comment]
`--rules` just passes path to file in `cakephp/upgrade` [/config/rector](https://github.com/cakephp/upgrade/tree/master/config/rector). There is no `cakephp42.php` there.

https://github.com/cakephp/upgrade/pull/154/files#diff-54737699ee4bbfa697bea45ec6fe60b8237133bf6dd8c789b20be9821180e9b2

Upgrade tool needs new `cakephp42.php` to load  `cakephp42.php` from https://github.com/rectorphp/rector/tree/master/config/set.

**Comment by othercorey** [comment]
rector is missing a `CAKEPHP_42` setlist as well.

**Comment by markstory** [comment]
Looks like Rector has a [cakephp_42](https://github.com/rectorphp/rector/blob/master/packages/set/src/ValueObject/SetList.php#L69) set list constant now.

**Comment by othercorey** [comment]
I just added it, but it's not in a release yet.

**Comment by othercorey** [comment]
Available in release.

**Comment by peterbaumert** [comment]
Still doesnt work for me i get
```
[ERROR] Undefined class constant 'CAKEPHP_42'
```
