### ISSUE TITLE
Undefined class constants: Fresh installation of upgrade tool fails on clean CakePHP3.9 skeleton

### ISSUE THREAD

**Issue by SomeUserUK** [cakephp/upgrade#169]
Hello,

Unless I am doing something very wrong, I cannot get a fresh installation of the upgrade tool to work on a clean CakePHP 3.9 skeleton

Steps to reproduce:

Install the CakePHP 3.9 skeleton into /tmp/cakestuff/myapp
```
cd /tmp
mkdir cakestuff
cd cakestuff
composer create-project --prefer-dist "cakephp/app:^3.8" myapp
```

Install the upgrade tool into /tmp/cakestuff/upgrade
```
git clone git://github.com/cakephp/upgrade
cd upgrade
composer install --no-dev
```

Attempt to upgrade /tmp/cakestuff/myapp
```
bin/cake upgrade /tmp/cakestuff/myapp
```

This produces the following output:
```
Moving templates
Renaming /tmp/cakestuff/myapp/src/Template
Moving sub directories of /tmp/cakestuff/myapp/templates
Recursively changing extensions in /tmp/cakestuff/myapp/templates
Moving locale files
Renaming /tmp/cakestuff/myapp/src/Locale
Applying cakephp40 Rector rules


 [ERROR] Undefined class constant 'CAKEPHP_40'


Rector applied successfully


 [ERROR] Undefined class constant 'CAKEPHP_40'


Rector applied successfully


 [ERROR] Undefined class constant 'CAKEPHP_40'


Rector applied successfully


 [ERROR] Undefined class constant 'CAKEPHP_40'


Rector applied successfully
Applying phpunit80 Rector rules


 [ERROR] Undefined class constant 'PHPUNIT_80'


Rector applied successfully
Next upgrade your composer.json.
```

**Comment by othercorey** [comment]
That looks like you're using an old version of rector/rector package which probably means your php version is too old.

**Comment by SomeUserUK** [comment]
I have just tried this on PHP8 as well, which results in the same (although slightly more detailed output)

```
bin/cake upgrade /tmp/cakestuff/myapp
Moving templates
Renaming /private/tmp/cakestuff/myapp/src/Template
Moving locale files
Renaming /private/tmp/cakestuff/myapp/src/Locale
Applying cakephp40 Rector rules


 [ERROR] Undefined constant Rector\Set\ValueObject\SetList::CAKEPHP_40


Rector applied successfully


 [ERROR] Undefined constant Rector\Set\ValueObject\SetList::CAKEPHP_40


Rector applied successfully


 [ERROR] Undefined constant Rector\Set\ValueObject\SetList::CAKEPHP_40


Rector applied successfully


 [ERROR] Undefined constant Rector\Set\ValueObject\SetList::CAKEPHP_40


Rector applied successfully
Applying phpunit80 Rector rules


 [ERROR] Undefined constant Rector\Set\ValueObject\SetList::PHPUNIT_80


Rector applied successfully
Next upgrade your composer.json.
```

**Comment by othercorey** [comment]
I can reproduce running the unit tests. It looks like a broken release somewhere. Unfortunately, rector doesn't have release notes, so hard to tell what is changed in any version.

**Comment by garas** [comment]
Rector 0.10.0 had split to multiple subpackages. 

Constants are now `Rector\CakePHP\Set\CakePHPSetList::CAKEPHP_40` in `rector/rector-cakephp` subpackage, 
`Rector\PHPUnit\Set\PHPUnitSetList::PHPUNIT_80` in `rector/rector-phpunit` subpackage.

**Comment by othercorey** [comment]
Unfortunate that changed in a patch release.

**Comment by ADmad** [comment]
The perils of using `~` instead of `^` for package on `0.x`.

**Comment by markstory** [comment]
We could change the constraint or pin to ^0.10 as I think the 4.2 rules are only in 0.10

**Comment by othercorey** [comment]
0.10.0 was working. This happened sometime during 0.10.x.

**Comment by othercorey** [comment]
One of the main issues we had with rector was way it tied cakephp version to rector versions. If we restricted the rector version, then users couldn't upgrade some cakephp versions.

It seems like 0.10.x package split should help that so I vote we make 0.10.x the minimum version. Hopefully the cakephp package won't need absolute latest rector package if we have issues in the future.

**Comment by othercorey** [comment]
@SomeUserUK Can you pull latest and try again?

**Comment by SomeUserUK** [comment]
> @SomeUserUK Can you pull latest and try again?

This has resolved the issue - thank you!
