### ISSUE TITLE
rector ~0.10.21 is satisfiable by rector/rector[0.10.x-dev] but these conflict with your requirements or minimum-stability

### ISSUE THREAD

**Issue by Mirelath** [cakephp/upgrade#171]
When performing the instructions as specified:

git clone git://github.com/cakephp/upgrade
cd upgrade
git checkout master
composer install --no-dev

This results in the following failure to resolve the rector dependency:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package rector/rector ~0.10.21 is satisfiable by rector/rector[0.10.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by othercorey** [comment]
I guess they deleted the package somehow. Rector has been pushing a lot of changes lately, some unstable.
