### ISSUE TITLE
Rector Upgrade command fails if path contains spaces

### ISSUE THREAD

**Issue by dmromanov** [cakephp/upgrade#174]
`bin/cake upgrade rector --rules phpunit80 ../myapp\ helper/tests/`
`bin/cake upgrade rector --rules cakephp40 ../myapp\ helper/src/`
`bin/cake upgrade rector --rules cakephp41 ../myapp\ helpre/src`

Output:
```
bin/cake upgrade rector --rules phpunit80 ../myapp\ helper/tests/

In FileSystemGuard.php line 31:
                                                                             
  Directory "/home/example/Пример/myapp" was not found.  
                                                                             

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--no-diffs] [--output-file OUTPUT-FILE] [--cache-debug] [--clear-cache] [--] [<source>...]


Rector applied successfully
```

I see two problems here:
- Upgrade command should handle paths containing spaces
- Upgrade command should report an error if upgrade failed.

Work around is to temporary rename the application folder to exclude spaces.

**Comment by othercorey** [comment]
Have you tried putting the path in quotes?

**Comment by dmromanov** [comment]
No need to: backslash escapes the space character just like the quotes.
Anyway, result is the same.

```
$ bin/cake upgrade rector --rules cakephp41 "../myapp helper/src/"

In FileSystemGuard.php line 31:
                                                                             
  Directory "/home/example/Пример/myapp" was not found.  
                                                                             

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--no-diffs] [--output-file OUTPUT-FILE] [--cache-debug] [--clear-cache] [--] [<source>...]


Rector applied successfully
```

**Comment by othercorey** [comment]
@markstory can you take a look?

**Comment by markstory** [comment]
I'm pretty sure we're handling paths with spaces correctly as we use `escapeshellarg()` when preparing the command we send to rector as seen here https://github.com/cakephp/upgrade/blob/e987c6e1a7da643e36d1263d88abba205b52bba5/src/Command/RectorCommand.php#L84-L105

There is no `FileSystemGuard` in the upgrade tool but there is one in rector. If you dump the `$command` variable on line 100 of the snippet I linked you should see a correctly quoted path and the command that the upgrade tool is going to run. If you are not able to have that command run from your terminal then the problem likely resides within rector.
