### ISSUE TITLE
working-dir parameter removed from rector 

### ISSUE THREAD

**Issue by Juanchimienti** [cakephp/upgrade#187]
When running the upgrade tool using rector 0.13.3 the following error appears:

`
                                              
  The "--working-dir" option does not exist.  
                                              

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [--no-progress-bar] [--no-diffs] [--output-format OUTPUT-FORMAT] [--debug] [--memory-limit MEMORY-LIMIT] [--clear-cache] [--port PORT] [--identifier IDENTIFIER] [--] [<source>...]

`

Looking at rectors release notes for tag 0.13.3 https://github.com/rectorphp/rector/releases/tag/0.13.3  I see that they removed that parameter. 

As a workaround I lock the rector version on the composer.json.
Changing "rector/rector": "^0.13.2" to "rector/rector": "0.13.2"

**Comment by othercorey** [comment]
Fixed. We use absolute paths so should work the same.

No idea why rector thought it was a good idea to remove a cli option in a patch release.
