### ISSUE TITLE
[ERROR] Could not resolve argument "Rector\Config\RectorConfig $rectorConfig" 

### ISSUE THREAD

**Issue by ishu-oct** [cakephp/upgrade#192]
Hi, I am trying to upgrade my application from cakephp 3.9.3 to the latest cakephp version.  While following the upgrade tools commands in[ 4.0 upgrade guide](https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html) in cakephp, I am facing the following error:

`bin/cake upgrade rector --rules  phpunit80 /home/example/my-app/tests`

```
[ERROR] Could not resolve argument "Rector\Config\RectorConfig $rectorConfig"  
         for "/home/example/upgrade/config/rector/phpunit80.php".
```
         
  Could anyone let me know how this has to be fixed? 
  Thanks in Advance.

**Comment by smarek** [comment]
Hey, i just hit the exact same issue, with "--rules cakephp44" argument, and the file being there

How did you fix this issue please?

```
> bin/cake upgrade rector --rules cakephp44 /home/smarek/Documents/PROJEKTY/CERTIFIX/GIT/Certifix_Produkce/src/


 [ERROR] Could not resolve argument "Rector\Config\RectorConfig $rectorConfig"  
         for                                                                    
         "/home/smarek/Documents/PROJEKTY/CERTIFIX/GIT/TOOLS/cakephp-upgrade-too
         l/config/rector/cakephp44.php".                                        


Rector applied successfully
```
