### ISSUE TITLE
 [ERROR] Class 'Rector\CakePHP\Set\CakePHPSetList' not found

### ISSUE THREAD

**Issue by narahari0601** [cakephp/upgrade#198]
Hi, 

I am getting below error while running the upgrade rector from 3.x to 4

`bin/cake upgrade rector --rules cakephp40 <application>\src
`
 ```
[ERROR] Class 'Rector\CakePHP\Set\CakePHPSetList' not found


Rector applied successfully
```

My rector version is  0.14.5
"rector/rector": "^0.14.5"
PHP: 7.4.30

**Comment by j3ll3nl** [comment]
It seems that DependaBot has updated Rector to a version without CakePHP rules. Setting back dependenxy to rector 13.03 seems to fix that.

**Comment by AdrianHL** [comment]
I'm getting this same error while doing a 4.3 to 4.4 upgrade.

**Comment by samsonasik** [comment]
The rector rules are moved here, just different branch https://github.com/cakephp/upgrade/pull/197

You can try branch: https://github.com/cakephp/upgrade/tree/import-rector-package while wait for it merged to main branch

/cc @markstory @othercorey probably time to integrate to main branch

**Comment by othercorey** [comment]
@AdrianHL pinned rector to 0.14.5 since the cakephp extension was dropped in a point release for some reason.

**Comment by samsonasik** [comment]
@othercorey just curious, why not merge import-rector-package branch to 4.x branch yet? From PR:

- https://github.com/cakephp/upgrade/pull/197

**Comment by othercorey** [comment]
We are working on it along with the cake5 release. We might split that into a cakephp-rector extension package.

**Comment by samsonasik** [comment]
Ok 👍
