### ISSUE TITLE
Missing CakePHP 5 rectors

### ISSUE THREAD

**Issue by LordSimal** [cakephp/upgrade#232]
I encountered the following issues while upgrading my app to the current CakePHP 5.0 RC1

* [x] Custom overwritten helpers (Form, Html etc.) need to have property types added (e.g. $_defaultWidgets, $helpers, $_defaultConfig)
* [x] Plugin classes need to have property types added for e.g. bootstrapEnabled
* [x] Custom Behaviors need to have property types added ($_defaultConfig)
* [x] Controller properties need to have types added (paginate, autorender etc.)
* [x] `orderDesc` and `orderAsc` on query objects need to be renamed to `orderByDesc` and `orderByAsc`
* [x] Fixture classes need to have property types added ($fixtures, $records, $fixtureStrategy)
* [x] Remove `useCommandRunner()` and `useHttpServer()` from tests since its not needed anymore
* [ ] `parent::__construct()` inside commands is not valid anymore since the BaseCommand has no constructor anymore
* [ ] Custom finders in table classes need to have `Cake\ORM\Query` changed to `Cake\ORM\Query\SelectQuery` for the first parameter and return type
* [ ] Custom finders in table classes also need to be adjusted to have the proper named params instead of the `$options` array
* [ ] I had a custom overwritten PaginatorHelper but the base class got an additonal `params` added inside the `_defaultConfig` array property. Therefore I got the error `Unsupported operand types: null + array` in `CORE/src/View/Helper/PaginatorHelper.php at line 163` without adding `'params' => []` to my overwritten PaginatorHelper
* [ ] Update `Connection::conect()` to `$connection->getDriver()->connect()`.

**Comment by LordSimal** [comment]
The custom finder related rectors would require us to create our own custom rules for that like we already did in the past. Haven't had the time yet though to tackle that.

**Comment by markstory** [comment]
>  Remove useCommandRunner() from tests since its not needed anymore

This will also require a custom rector. We should also remove usage of `useHttpServer()` from tests as that method isn't in use anymore either.

**Comment by LordSimal** [comment]
as discussed with Mark Story we wont create any further Cake 5.0 rectors
