### ISSUE TITLE
Some more rector rules

### ISSUE THREAD

**Issue by dereuromark** [cakephp/upgrade#262]
Components

    public $components = [

to

    public array $components = [

---

View

    protected $layout = 

to

    protected string $layout = 

---

Controller

    protected $modelClass = 

to

    protected ?string $modelClass =

**Comment by LordSimal** [comment]
Shouldn't `modelClass` be `defaultTable`?
I guess both are valid since ModelAwareTrait and TableLocatorAwareTrait are possible to use.
