### ISSUE TITLE
Migrate from cake 3.10.1 to 4.x [ERROR] Could not process  | Child process timed out after 120 seconds". On line: 108

### ISSUE THREAD

**Issue by pragnesh-lspl** [cakephp/upgrade#282]
280/771 [▓▓▓▓▓▓▓▓▓▓░░░░
 [ERROR] Could not process                                                      

 520/771 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  67%
         "/var/www/html/upgrade/vendor/rector/rector/vendor/symplify/easy-parall
         el/src/ValueObject/ParallelProcess.php" file, due to:                  

 711/771 [▓▓▓▓▓▓▓▓▓▓▓▓�
         "Child process timed out after 120 seconds". On line: 108              

 751/771 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░]  97%

 [ERROR] Could not process some files, due to:                                  
         "Reached system errors count limit of 50, exiting...".
         
    I have used: bin/cake upgrade /app_path. 
    Is there a solution for this?

**Comment by dereuromark** [comment]
Try using specific src/ path here, never the whole app path, for memory reasons.
