### ISSUE TITLE
Question - Can we upgrade cakePHP version 2.X  to the latest version using upgrade tool? 

### ISSUE THREAD

**Issue by Suraj-1999-13** [cakephp/upgrade#286]

**Comment by markstory** [comment]
Not directly. Each major version needs to be completed separately. And the upgrade process from 2 -> 3 is particularly hard due to massive changes in the ORM that require manual updates.

**Comment by Suraj-1999-13** [comment]
Thank you!
Our customer has two different projects one of them uses CakePHP 2.1 and the other one uses 3.7.  
Customers want to upgrade both projects to version 5.0, So just want to clear some points,
1 - Is it possible to upgrade 3.7 to 5.0 using an upgrade or not?
2 - How much manual work needs to be done like 20% manual and 80% automatic using tools?
3 - Is there any solution available to upgrade the 2.1 version to the latest or is everything to be done manually?

**Comment by markstory** [comment]
>  1 - Is it possible to upgrade 3.7 to 5.0 using an upgrade or not?

Yes, but not in one step. The recommended path is to go from 3.7 -> 3.10, and address any deprecations that are coming up. Then go from 3.10 -> 4.0. Once you're at 4.0, upgrade one minor at at time until you get to 4.5, and solve the deprecations there.  Once you have deprecations solved for 4.x, go from 4.x -> 5.0.

>  2 - How much manual work needs to be done like 20% manual and 80% automatic using tools?

It depends on the application.

>  Is there any solution available to upgrade the 2.1 version to the latest or is everything to be done manually?

There is no automated solution. The upgrade tool from 2 -> 3 takes care of a few concerns but doesn't address the most complex parts of the upgrade.
