### ISSUE TITLE
Adjust method declarations/callbacks for rules

### ISSUE THREAD

**Issue by dereuromark** [cakephp/upgrade#70]
beforeValidate/afterValidate
should now be
beforeRules/ afterRules

Any other changes from the recent validation rework that need to be addressed?

**Comment by markstory** [comment]
renaming the methods is only part of the problem. It is a good start but not the totality of the changes that people will need to make.

**Comment by lorenzo** [comment]
I think it would be misleading to do a blind rename of the methods, as most of the logic would not apply at all.

**Comment by dereuromark** [comment]
There will sure be more changes to be done manually. Closing then for now.
