### ISSUE TITLE
Cake 1.3

### ISSUE THREAD

**Issue by kvz** [cakephp/upgrade#77]
I have a site that's still on CakePHP 1.3 (yeah I know). Any chance this tool could also do a best effort upgrade of that ancient version? I'm happy to do the cleaning up afterwards, but it would already be a big help if this tool could handle 80% of the most common search & replaces : )

**Comment by ceeram** [comment]
CakePHP 2.x has a built in upgrade shell to do that.
https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Console/Command/UpgradeShell.php
This upgrade project is to go from 2.x to 3.0

**Comment by ceeram** [comment]
And good to see you back at CakePHP ;)

**Comment by kvz** [comment]
That helps already - thanks! :)

**Comment by ceeram** [comment]
@kvz You might want to have a look at the upgrade docs as well:
http://book.cakephp.org/2.0/en/appendices/2-0-migration-guide.html

**Comment by kvz** [comment]
:+1:
