### ISSUE TITLE
cake upgrade all - PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found ...

### ISSUE THREAD

**Issue by alexmanrique** [cakephp/upgrade#81]
Hi,

when I'm trying to execute "upgrade all" of my old cakephp application I get an error:
```
CakeSessionHandlerInterface is not in the implicit class map
DataSource is not in the implicit class map
CakeTestModel is not in the implicit class map
TestPluginAppModel is not in the implicit class map
TestPluginAppModel is not in the implicit class map
TestPluginAppModel is not in the implicit class map
TestPluginAppModel is not in the implicit class map
PHPUnit_Framework_TestResult is not in the implicit class map
SimpleTestCase is not in the implicit class map
ClassRegistry is not in the implicit class map
CakeTestSuiteDispatcher is not in the implicit class map
PHPUnit_Runner_StandardTestSuiteLoader is not in the implicit class map
PHPUnit_TextUI_TestRunner is not in the implicit class map
array is not in the implicit class map
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /Users/my_user_name/git/upgrade/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 29
```

why I'm receiving this error?
I have phpunit installed in my system, (it seams that it cannot found phpunit in the PATH)
$> phpunit --version 
PHPUnit 4.6.4 by Sebastian Bergmann and contributors.

**Comment by dereuromark** [comment]
I ran into the same issue today, I fixed it by simple adding phpunit as composer dependency on my branch:
https://github.com/dereuromark/upgrade/commit/7b02971e6526bf10933b5af53abb3c100fdb1f43#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R10

Maybe you should PR that.

**Comment by alexmanrique** [comment]
I get the following message if I add phpunit in composer.json
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpunit/phpunit  could not be found, it looks like its name is invalid, " " is not allowed in package names.
```

do you get this error?

thanks

**Comment by dereuromark** [comment]
How did you add it? exactly?

**Comment by alexmanrique** [comment]
I copy what you add in the composer.json 
```
"require": {
                "cakephp/cakephp": "~3.0",
                "cakephp/app": "3.0.*",
                "cakephp/plugin-installer": "dev-master",
                "phpunit/phpunit ": "*"
        },
```
I will clone your fork, and see if it works in my laptop

**Comment by dereuromark** [comment]
Since when is a space in your name valid? :P I told you to double check your require statement.

**Comment by alexmanrique** [comment]
Yes you're right, I had an extra space ... I have been able to update finally my cakephp project. thanks

**Comment by markstory** [comment]
Sounds like this has been resolved.

**Comment by dereuromark** [comment]
Not really :)
This should probably me merged first.
