### ISSUE TITLE
Errors during "upgrade namespaces" and other gotchas

### ISSUE THREAD

**Issue by glkaup** [cakephp/upgrade#86]
I've done the following:
Download and copy contents into E:\myapp.git
```
cd to folder E:\myapp.git
E:\myapp.git>composer self-update
E:\myapp.git>composer update          // brought in cake 3.0.8
```

The first issue I had to solve was that the docs do NOT indicate that a command line version of git.exe needed to be available.  Since I use SmartGit on Windows, I had to add a new entry to the PATH environment variable.

My current directory is the folder of my project (E:\myapp.git) and I use the following command to start the conversion process:

FIRST STEP:
```
E:\myapp.git>.\bin\cake upgrade locations E:\myapp.git > E:\UPG_locations.txt 2>&1
```

This produces output beginning with...
```
Welcome to CakePHP v3.0.8 Console
App : src
Path: E:\myapp.git\src\
Welcome to CakePHP v3.0.8 Console
App : src
Path: E:\myapp.git\src\

Processing ROOT\.editorconfig
```
... etc ...

and with out error.  But to get this to work, two folders (Data and Database) that I had in my app folder had to be removed.  They contained large zip and db files which forced the upgrade tool to try and allocate massive amounts of memory... which failed.  I removed those two folders, and now it runs fine.  After each upgrade command, I have done a backup of the entire project folder!

NEXT STEP:
```
E:\myapp.git>.\bin\cake upgrade namespaces E:\myapp.git > E:\UPG_namespaces.txt 2>&1
```

Which produces a very large output file including many errors:

```
error: Could not access ''E:\myapp.git\tmp\upgrade\dd8a59b3e6b24728af45f746520a60a93443b424''
Update ROOT\app\Config\acl.php
error: Could not access ''E:\myapp.git\tmp\upgrade\0c11c967815dc17a961003fac3ca880d57865a2b''
Update ROOT\app\Config\database.php


error: Could not access ''E:\myapp.git\tmp\upgrade\70f6bec3dc3ca26f9ce8bd5fb6906f7ec33d8ce0''
Update ROOT\app\Console\Command\AppShell.php
error: Could not access ''E:\myapp.git\tmp\upgrade\a9818200390c980373d7f84590337e18f225b89c''
Update ROOT\app\Controller\AppController.php
```

The file app\database.php has been modified with a "namespace app\Config"  even though there are errors!
I have stopped here... since I have been here several times before and cannot find a solution.  In past attempts, I never end up with the new \src\Controllers or most of the other folders created as expected.  Sorry, but here I am and really need some help to proceed.

Proceeded with next command, as listed on this site... rename_classes had more errors much like namespaces above.

Then rename_classes get the following error:
```
Parse error: syntax error, unexpected '$class' (T_VARIABLE), expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) or \\ (T_NS_SEPARATOR) in E:\ezshoot.git\src\Shell\Task\AppUsesTask.php on line 17
```

I'm done!  If I'm forced to re-bake and organized the old code... cakePHP 3.0 will NOT be used!

I am willing to supply the backups and output files, but only to the developers of the upgrade tool.

Thanks in advance for any assistance,
GLK

**Comment by lorenzo** [comment]
I think one of the problems you have is that you are not running a php version that is compatible with cake 3. For example looking at this error you got:

> Parse error: syntax error, unexpected '$class' (T_VARIABLE), expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) or \ (T_NS_SEPARATOR) in E:\ezshoot.git\src\Shell\Task\AppUsesTask.php on line 17

If we take a look at line 17: https://github.com/cakephp/upgrade/blob/master/src/Shell/Task/AppUsesTask.php#L17

That line is jut standard php syntax. The fact that you are getting a syntax error there tells that you are not using the right version.

I haven't personally used this tool, and I'm sure there is plenty room for improvements, but this is offered as a help to users wanting to upgrade, so it take cares of then repetitive boring tasks. There is no need to use this tool in order to upgrade, you can also do some of the work manually (which is what I ahve done in every case)

Also, if I were you, I would try to run the commands in a unix-like system, where most of the tools that it requires (such as git) are available by default.

**Comment by glkaup** [comment]
lorenzo,

Thank you for your input, but I'm afraid further research shows something else.  phpinfo show 5.6.8.  The contents of AppUsesTask  lines 15 - 25 are changed very dramatically after running AppUses!

Just after running the NamespacesTask, the contents are:

    namespace Cake\Upgrade\Shell\Task;
    
    use Cake\Console\Shell;
    use Cake\Upgrade\Shell\Task\BaseTask;
    
    /**
    * App Uses Task.
     *
     * Updates App::uses() calls.
     */
    class AppUsesTask extends BaseTask

AFTER running AppUsesTask, the contents are:
    namespace Cake\Upgrade\Shell\Task;
    
    use $class;\n";
    use ' . $use;
    use .+;/", $contents);
    use <Classname>;
    use = $matches[2] . '\' . $matches[3] . '\' . $matches[1];
    use = $matches[2] . '\' . substr($matches[3], 4) . '\' .$matches[1];
    use = 'App\' . substr($use, 5);
    use = 'Cake\' . $matches[2] . '\' . $matches[1];
    use = str_replace('/', '\', $use);
    use Cake\Console\Shell;
    use Cake\Core\App;
    use Cake\Upgrade\Shell\Task\BaseTask;
    use ChangeTrait;
    
    /**
     * App Uses Task.
     *
     * Updates App::uses() calls.
     */
    class AppUsesTask extends BaseTask

As for doing all the changes manually...  I really doubt that I will do that... I will probably move to another framework or just roll my own.  It will take about the same amount of time and at least I can choose how much complication and code bloat I want.

As for running on *nix... ok I suppose (If the client wanted that), but what's wrong with a little documentation.  I keep reading that cakePHP has "Great docs"  but here we are in a very scary place, about to upgrade real life projects, and the docs don't even mention that git will be used to move files around.

I am very disappointed with the state of cake these days.  It took two years to really learn most of what cake had to offer, and now... throw it away in the name of ORM and another college professor's call to make the "perfect code framework."   I need a framework that WORKS!

Lorenzo, I do thank you for your response, I only wish the fix were that simple.
GLK

**Comment by lorenzo** [comment]
@glkaup It looks like you have the upgrade shell code inside the app you are trying to run?

That would be the explanation for the tool running on itself. There are some instructions here on how it should be used: https://github.com/cakephp/upgrade#usage

You can also read some notes about it in this blog post: http://mark-story.com/posts/view/upgrading-to-cakephp-3-0

> ... throw it away in the name of ORM

No one is asking you to throw away your code. If it is working great for you, then keep working with it. Cake 2.x is not going to die overnight.

Let me know, though, if you need any help during the upgrade process. I can gladly offer some pointers on the direction to take.

**Comment by glkaup** [comment]
OK, I'm here at github following the docs for the upgrade tool. That's how I got here!
But WHY am I looking for docs on Mark Story's blog?  I'm well aware that Mark has a great deal of input for cakePHP, but isn't the cakePHP website the place for documentation!?

Mr. Story's blog was indeed very helpful... Thank you for the link!

Also, since I'm ranting a little here... why can't cakePHP decide on the forum that it wants for official help... is it google, google+, stackoverflow, or Mr. Story's blog!  Of course I understand the everyone thinks they have a better mousetrap, but as a product cakephp is spread all over the place.  That may be considered a great open source idea, but for those of us wanting Documentation, it is quite unreliable.

**Comment by markstory** [comment]
@glkaup My blog is not to be considered official documentation. Its simply a place I share things I've learned.

Would it have been helpful if the installation installation and usage examples in the README were more detailed?

**Comment by lorenzo** [comment]
@markstory I think we could move the docs to the book as we have done with other plugins. What do you think?

**Comment by markstory** [comment]
@lorenzo I think that would be good. I can take care of that.

**Comment by glkaup** [comment]
@markstory Absolutely.  Isn't that where all the documentation belongs.  I would prefer NOT to discuss my feelings on cakePHP in public any further.  I'm would make myself available privately if you really want a cakePHP fan's input, without getting into a public flame war that only leads nowhere!

**Comment by markstory** [comment]
@glkaup I don't think anything you've said so far is leading to a public flamewar. The feedback you've given so far as been helpful to improve the documentation :smile:

**Comment by markstory** [comment]
Going to close this as I hope the improved documentation helps fix some of the errors you ran into. If there is additional documentation that would help, let me know. I'm happy to write more documentation :smile:
