### ISSUE TITLE
Command line unable to access file

### ISSUE THREAD

**Issue by trante** [cakephp/upgrade#87]
I installed composer, I made this:

```cd /path/to/upgrade```
```bin/cake upgrade all /home/mark/Sites/my-app```
Then I get tons of error like this in windows command shell.

```error: Could not access ''C:\mydir\upgrade\tmp\upgrade\a2d4223f62e3499a84b6ca30be24bfdb4cb6de40''
Update C:\mydir\myapp\lib\Cake\View\Helper\CacheHelper.php
error: Could not access ''C:\mydir\upgrade\tmp\upgrade\7fbe7651712387f351b1eb670b14c18e1161fcb8''
Update C:\mydir\myapp\lib\Cake\View\Helper\HtmlHelper.php
error: Could not access ''C:\mydir\upgrade\tmp\upgrade\2301f9bed1167ddb29ca4e06706d0d21bd015766''
Update C:\mydir\myapp\lib\Cake\View\Helper\NumberHelper.php
error: Could not access ''C:\mydir\upgrade\tmp\upgrade\e71af0cbc7df7ff76e801c5fb06ec07ee7f45233''
Update C:\mydir\myapp\lib\Cake\View\Helper\PaginatorHelper.php
error: Could not access ''C:\mydir\upgrade\tmp\upgrade\1b04b5a763ca4e798d1e176111e49008b7486724''
Update C:\mydir\myapp\lib\Cake\View\Helper\TextHelper.php
error: Could not access ''C:\mydir\upgrade\tmp\upgrade\f8ead667c131610c1f70f38d10c7122b34d9a7fc''
Update C:\mydir\myapp\lib\Cake\View\Helper\TimeHelper.php
error: Could not access ''C:\mydir\upgrade\tmp\upgrade\4a2c2e7f3f7e9faf744d10e6e1f3ff24bead7f08''
Update C:\mydir\myapp\lib\Cake\View\HelperCollection.php```

I run command shell as administrator. What would be the problem ? 

When I check folder during operation, I can see that temporary file exists in folder.

**Comment by markstory** [comment]
Do the files that are listed as missing exist?

**Comment by trante** [comment]
Yes. If I interrupt process, I can see that files exists.
If I don't interrupt, these temp files are deleted automatically.

**Comment by markstory** [comment]
I am not sure then. I am not overly familiar with permissions issues on windows.

**Comment by dereuromark** [comment]
Yeah I just ignored those errors. It still works, though.

**Comment by ndm2** [comment]
The problem here is that the path arguments are passed with single quotes. The Windows CLI will pass them as if they belong to the path. Look closely at the error, it shows double single quotes `''`.

https://github.com/cakephp/upgrade/blob/cafe211ea14ea00a69b754e44581b1fde820912e/src/Shell/Task/StageTask.php#L176

The `git diff` call should use `escapeshellarg()` for the path arguments, just like it's being done in the other calls.
