### ISSUE TITLE
Various GIT problems on Windows

### ISSUE THREAD

**Issue by ndm2** [cakephp/upgrade#88]
There are a few problems when using GIT on Windows.

* [**`;` is used as a separator**](https://github.com/cakephp/upgrade/blob/cafe211ea14ea00a69b754e44581b1fde820912e/src/Shell/Task/StageTask.php#L111) the the `cd` and `git` commands, which isn't supported, instead `&` or `&&` need to be used.

* The shell assumes that GITs `mkdir` command is globally available, it uses `mkdir -p path`, which will fail on Windows in case GIT is installed with only the `git.exe` in the PATH (this is default option), as then the default `mkdir` command will be used wich doesn't support the `-p` argument, and create a path named `-p` instead.

* [**Moving the `__` appended files**](https://github.com/cakephp/upgrade/blob/cafe211ea14ea00a69b754e44581b1fde820912e/src/Shell/Task/StageTask.php#L156) doesn't work. This results in an "_No such file or directory_" error for whatever reason, not sure what the problem here is, maybe some kind of race condition.

I'm using Windows 7 x64 and GIT 1.9.5.msysgit.1

**Comment by lorenzo** [comment]
Using windows is indeed a big handicap for a php developer :(

**Comment by ndm2** [comment]
Never really had much problems though, luckily I don't need to use the upgrade shell myself, I just read some issues posted on SO and wanted to check what's wrong, which is when I've stumbled over it :wink:

**Comment by markstory** [comment]
Maybe a nice person who does use windows can help fix these issues. I have little experience woth windows to be honest.

**Comment by ndm2** [comment]
I can give it a try... just one question, why aren't the files being git moved directly, why create `xyz__` files first?

**Comment by markstory** [comment]
@ndm Many case insensitive, but case preserving filesystems will screw up case renames. HFS+ on OSX is notorious for this.

**Comment by ndm2** [comment]
Ah ok, got it, I remember seeing similar stuff on Windows...

**Comment by ndm2** [comment]
Looks like I got fooled by the error, it wasn't actually complaining about the `__` files, but about the target directory which was missing because of failing `mkdir -p`. Everything seems fine once the directory is being created just like in the _move only_ part.. Should all be covered by #92 now.
