### ISSUE TITLE
Closing directory separator is needed for the `locations` task to work properly

### ISSUE THREAD

**Issue by ndm2** [cakephp/upgrade#89]
When passing a path to the shell that has no closing directory separator, like

```
upgrade locations my/path
```

the relative path extracted in `LocationsTask::_relativeFromRoot()` will start with a leading separator when the root is being stripped from it

https://github.com/cakephp/upgrade/blob/cafe211ea14ea00a69b754e44581b1fde820912e/src/Shell/Task/LocationsTask.php#L140

wich will finally result in a path fragment with double leading separators trying to be replaced in

https://github.com/cakephp/upgrade/blob/cafe211ea14ea00a69b754e44581b1fde820912e/src/Shell/Task/LocationsTask.php#L51

causing nothing to be replaced, and thus no files being moved.

**Comment by othercorey** [comment]
Closing 2.x => 3.x issues.
