### ISSUE TITLE
Moving directories will fail

### ISSUE THREAD

**Issue by ndm2** [cakephp/upgrade#91]
I haven't tested it yet, but just from the warnings spit out by my IDE, I can see that this will fail

https://github.com/cakephp/upgrade/blob/master/src/Shell/Task/StageTask.php#L234-L244

since `_findFiles()` doesn't exist (and doesn't even take the source path), just like the `$new` variable.

Are there actually situations where folders need to be moved? I never stumbled over this in my manual tests.

**Comment by markstory** [comment]
I don't think we move directories often. Generally we use rename instead.

**Comment by othercorey** [comment]
Closing 2.x => 3.x issues.
