### ISSUE TITLE
Class is not in the implicit class map

### ISSUE THREAD

**Issue by bastienjalbert** [cakephp/upgrade#97]
When I try to upgrade my application I get a lot of warning/error, I don't know why they happend, is there something to do with compose.json ?

<code>ClassRegistry is not in the implicit class map</code>
<code>Processing /var/www/temp_avoid/app/lib/Cake/tests/TestCase/src/Template/MediaViewTest.php </code>
<code>Processing /var/www/temp_avoid/app/lib/Cake/tests/TestCase/src/Controller/ControllerMergeVarsTest.php</code>
<code>Processing /var/www/temp_avoid/app/lib/Cake/tests/TestCase/src/Controller/Component/EmailComponentTest.php</code>
<code>Email is not in the implicit class map</code>
<code>EmailComponentTest is not in the implicit class map</code>
<code>DebugCompTransport is not in the implicit class map</code>
<code>ClassRegistry is not in the implicit class map</code>
<code>Type is not in the implicit class map</code>

**Comment by markstory** [comment]
Looks like you are applying the upgrade tool to the cakephp libraries. You might want to skip those directory trees.

**Comment by bastienjalbert** [comment]
I'm trying to apply the upgrade tool to the cake app (2.3.0) root directory .. Maybe should I start a blank cakephp 3 app and upgrading all by hands, my 2.3 app seems to be really dirty (like too much things done directly into views where these things have to be done in controller for example), the upgrade tool is not always the best solution I think, I'm really perplexed now...

**Comment by markstory** [comment]
@bastienjalbert The upgrade tool won't help with structural issues, but will help with renaming methods etc. Instead of running it on the lib/ directory, just run it on the app/ directory.

**Comment by bastienjalbert** [comment]
I wasn't running upgrade tool in lib/ folder before, I was trying on the root directory of my application.
I got the same result if I run the upgrade tool on the app/ directory (lot of "is not in the implicit class map", and some code not upgrade (still App::uses for example)).

**Comment by markstory** [comment]
The lib directory is inside the root directory, at least based on paths like `/var/www/temp_avoid/app/lib/Cake/tests/TestCase/src/Controller/Component/EmailComponentTest.php`.

**Comment by bastienjalbert** [comment]
Oh yes, I tried removing lib folder in app/, but It's the same, I get a lot of warning ... And some App:uses still here

**Comment by arkayz** [comment]
Any luck with this?

**Comment by bastienjalbert** [comment]
No..., but I updated to the last 2.x version instead
