### ISSUE TITLE
Error while upgrading my Cake 2.3.5 to Cake 3.0

### ISSUE THREAD

**Issue by purnarao** [cakephp/upgrade#98]
I followed the following steps - 
- I have my project in vhosts, project folder name is "old_version" which was built on Cakephp 2.3.5
- Now going inside - cd old_version, there I run "git clone git://github.com/cakephp/upgrade.git" command and downloaded a folder with name "upgrade".
- Now moving into "upgrade" folder cd upgrade, there I installed composer by running the command "curl -sS https://getcomposer.org/installer | php".
- Composer  is downloaded into "upgrade" folder. 
- Now when I execute "bin/cake upgrade all ../old_version/app" , there i am getting an error in terminal that "require(/var/www/vhosts/old_version/upgrade/vendor/cakephp/cakephp/src/Core/ClassLoader.php): failed to open stream: No such file or directory in /var/www/vhosts/old_version/upgrade/config/bootstrap.php on line 32
  PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/talenthire_old/upgrade/vendor/cakephp/cakephp/src/Core/ClassLoader.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/vhosts/talenthire_old/upgrade/config/bootstrap.php on line 32
  "
- The issue is when I download shell from "git clone git://github.com/cakephp/upgrade.git" I was not getting any vendor folder within that.

Please suggest me with all required steps,  how can I upgrade my Cakephp V 2.3.5 to Cakephp V 3.0

**Comment by markstory** [comment]
That fatal error looks like the installation process did not work. Did you run `composer.phar install` after downloading composer? You need to do that.

**Comment by purnarao** [comment]
I have installed composer.phar in my project @markstory. But some how its so confusion to upgrade 2.3.5 version to 3.0. If someone have complete steps for upgrading Cakephp version 2.3.5 to 2.7 atleast, then please share with me those steps. I need it very badly. Because my website with version 2.3.5 is getting very low performance.

**Comment by dereuromark** [comment]
@purnarao Make sure you read each migration guide.
Also check https://github.com/dereuromark/cakephp-upgrade - it contains some more info and automation tools.

**Comment by utkarshjain-daffodilsw** [comment]
@purnarao I also wants to upgrade my CakePHP version from 2.3.1 to 3.6. Can you please suggest me the ways to do it?
Should I need to download the upgrade tool into the same directory which I want to upgrade or into the root folder?
It's really bit confusing for me.
Any help is appreciated....!

**Comment by dereuromark** [comment]
For 3.6 it might be better now to also check [rector](https://www.dereuromark.de/2018/03/14/cakephp-3-6-is-coming/#migration-tooling) as tool. But before that, yeah, check out the repo as documented (!) as standalone package and run it over the app as path argument.

**Comment by utkarshjain-daffodilsw** [comment]
Thanks, @dereuromark for the speedy answer...
I just take the clone for upgrade tool in my directory. 
Then I run the command bin/cake upgrade --help
It through me below error.
I also run the composer install
![screenshot from 2018-12-11 15-35-32](https://user-images.githubusercontent.com/38935568/49793114-6c42c800-fd5a-11e8-99e4-87ea7708b7a5.png)

**Comment by dereuromark** [comment]
Yeah the tool itself now is super outdated. My branch might be a bit better, but not much.
You would need to fix also that tool first a bit more.

**Comment by purnarao** [comment]
I did everything and finally ran this command "bin/cake upgrade all ../old_version/app".  Got the below error message - 
"Exception: If config is null, key must be an array. in [/var/www/vhosts/old_version/upgrade/vendor/cakephp/cakephp/src/Core/StaticConfigTrait.php, line 80". 
Please help me out, as I was stuck here from few days.

**Comment by garas** [comment]
Add `return $config;` in the end of `app.php`. Or `return [ ... whole array ... ];`.

**Comment by purnarao** [comment]
I already did that @garas . But still no chance. Look at my app.php file code.
`<?php
$config = [
/**
 * Debug Level:
 *
 * Production Mode:
 * 0: No error messages, errors, or warnings shown. Flash messages redirect.
 *
 * Development Mode:
 * 1: Errors and warnings shown, model caches refreshed, flash messages halted.
 * 2: As in 1, but also with full debug messages and SQL output.
 *
 */
	'debug' => 2,

/**
 * Configure basic information about the application.
 *
 * - namespace - The namespace to find app classes under.
 * - encoding - The encoding used for HTML + database connections.
 * - base - The base directory the app resides in. If false this
 *   will be auto detected.
 * - dir - Name of app directory.
 */
	'App' => [
		'namespace' => 'Cake\Upgrade',
		'encoding' => 'UTF-8',
		'base' => false,
		'dir' => 'src'
	],

/**
 * Configure the cache adapters.
 */
	'Cache' => [
		'default' => [
			'engine' => 'File',
		],

	/**
	 * Configure the cache used for general framework caching.  Path information,
	 * object listings, and translation cache files are stored with this configuration.
	 */
		'_cake_core_' => [
			'className' => 'File',
			'prefix' => 'myapp_cake_core_',
			'path' => CACHE . 'persistent/',
			'serialize' => true,
			'duration' => '+10 seconds',
		],

	/**
	 * Configure the cache for model and datasource caches.  This cache configuration
	 * is used to store schema descriptions, and table listings in connections.
	 */
		'_cake_model_' => [
			'className' => 'File',
			'prefix' => 'my_app_cake_model_',
			'path' => CACHE . 'models/',
			'serialize' => 'File',
			'duration' => '+10 seconds',
		],
	],

/**
 * Configure the Error and Exception handlers used by your application.
 *
 * By default errors are displayed using Debugger, when debug > 0 and logged by
 * Cake\Log\Log when debug = 0.
 *
 * In CLI environments exceptions will be printed to stderr with a backtrace.
 * In web environments an HTML page will be displayed for the exception.
 * While debug > 0, framework errors like Missing Controller will be displayed.
 * When debug = 0, framework errors will be coerced into generic HTTP errors.
 *
 * Options:
 *
 * - `errorLevel` - int - The level of errors you are interested in capturing.
 * - `trace` - boolean - Whether or not backtraces should be included in
 *   logged errors/exceptions.
 * - `log` - boolean - Whether or not you want exceptions logged.
 * - `exceptionRenderer` - string - The class responsible for rendering
 *   uncaught exceptions.  If you choose a custom class you should place
 *   the file for that class in app/Lib/Error. This class needs to implement a render method.
 * - `skipLog` - array - List of exceptions to skip for logging. Exceptions that
 *   extend one of the listed exceptions will also be skipped for logging.
 *   Example: `'skipLog' => array('Cake\Error\NotFoundException', 'Cake\Error\UnauthorizedException')`
 */
	'Error' => [
		'errorLevel' => E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED,
		'exceptionRenderer' => 'Cake\Error\ExceptionRenderer',
		'skipLog' => [],
		'log' => true,
		'trace' => true,
	],

/**
 * Configures logging options
 */
	'Log' => [
		'debug' => [
			'className' => 'Cake\\Log\\Engine\\FileLog',
			'file' => 'debug',
			'levels' => ['notice', 'info', 'debug'],
		],
		'error' => [
			'className' => 'Cake\\Log\\Engine\\FileLog',
			'file' => 'error',
			'levels' => ['warning', 'error', 'critical', 'alert', 'emergency'],
		],
	],

	'Session' => [
		'defaults' => 'php',
	],
];
return $config;`

**Comment by garas** [comment]
Option 1: 

`cakephp/upgrade` is not updated for CakePHP 3.7.

Try to downgrade by executing `composer require cakephp/cakephp:3.5.* --update-with-dependencies` in `upgrade/` directory.

---

Option 2:

You get that error, I guess, because config is missing `Datasources` and `EmailTransport` keys, and they are used as `null` in

https://github.com/cakephp/upgrade/blob/f8f1a5ed10cad85531b46d7bc5041f04b9a2d203/config/bootstrap.php#L121-L125

You can try comment email/datasource lines as they are not used by Upgrade app

**Comment by purnarao** [comment]
Thank you @garas . It worked. I will keep post, if I face any other major issues while upgrading. Still having few issues.

**Comment by garas** [comment]
Closing as it was fixed in #123.
